default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host:     <%= ENV.fetch("DB_HOST", "localhost") %>
  port:     5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: grpc_app_development

test:
  <<: *default
  database: grpc_app_test

production:
  <<: *default
  database: grpc_app_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
