# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sum.proto

require 'google/protobuf'


descriptor_data = "\n\tsum.proto\x12\x03sum\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x36\n\nSumService\x12(\n\x03\x61\x64\x64\x12\x0f.sum.SumRequest\x1a\x10.sum.SumResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Sum
  SumRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.SumRequest").msgclass
  SumResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sum.SumResponse").msgclass
end
