# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sum.proto for package 'sum'

require 'grpc'
require 'sum_pb'

module Sum
  module SumService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sum.SumService'

      rpc :add, ::Sum::SumRequest, ::Sum::SumResponse
    end

    Stub = Service.rpc_stub_class
  end
end
